const fs = require('fs');
const path = './src/utils/injectEditorScript.ts';

let content = fs.readFileSync(path, 'utf8');

const target = `          } else if (action === 'setVariable' || action === 'toggleVariable') {
            window.parent.postMessage({
              type: 'FORGE_EXECUTE_ACTION',
              action,
              key: args[0],
              value: args.slice(1).join(':')
            }, '*');
          }`;

const replacement = `          } else if (action === 'setVariable' || action === 'toggleVariable') {
            window.parent.postMessage({
              type: 'FORGE_EXECUTE_ACTION',
              action,
              key: args[0],
              value: args.slice(1).join(':')
            }, '*');
          } else {
            // Fallback: Treat as raw Javascript (generated by AI Logic Builder)
            try {
              // Create a function to execute the raw JS in the context of the element
              const fn = new Function('event', actionStr);
              fn(window.event);
            } catch (err) {
              console.error('Failed to execute AI Logic:', err);
            }
          }`;

if (content.includes(target)) {
  content = content.replace(target, replacement);
  fs.writeFileSync(path, content);
  console.log("Successfully patched injectEditorScript.ts");
} else {
  console.log("Could not find the target in injectEditorScript.ts");
}
