const fs = require('fs');
const file = 'src/components/ProjectSettingsModal.tsx';
let code = fs.readFileSync(file, 'utf8');

code = code.replace('seo: Record<string, string>;', 'seo: Record<string, string>;\n  payments?: Record<string, string>;\n  onUpdatePayments?: (payments: Record<string, string>) => void;');
code = code.replace('export const ProjectSettingsModal: React.FC<ProjectSettingsModalProps> = ({ seo, onUpdateSEO, auth, onUpdateAuth, onClose }) => {', 'export const ProjectSettingsModal: React.FC<ProjectSettingsModalProps> = ({ seo, onUpdateSEO, auth, onUpdateAuth, payments = {}, onUpdatePayments, onClose }) => {');
code = code.replace('const [firebaseConfig, setFirebaseConfig] = useState(auth?.firebaseConfig || \'\');', 'const [firebaseConfig, setFirebaseConfig] = useState(auth?.firebaseConfig || \'\');\n  const [stripePublishableKey, setStripePublishableKey] = useState(payments?.stripePublishableKey || \'\');\n  const [stripeSecretKey, setStripeSecretKey] = useState(payments?.stripeSecretKey || \'\');');

code = code.replace('onUpdateAuth({', 'if (onUpdatePayments) {\n      onUpdatePayments({\n        stripePublishableKey,\n        stripeSecretKey\n      });\n    }\n    onUpdateAuth({');

code = code.replace('<button\n            onClick={() => setActiveTab(\'auth\')}', '<button\n            onClick={() => setActiveTab(\'auth\')}\n            className={`px-4 py-3 text-sm font-medium border-b-2 transition-colors ${activeTab === \'auth\' ? \'border-amber-500 text-amber-500\' : \'border-transparent text-hall-500 hover:text-hall-900 dark:hover:text-white\'}`}\n          >\n            Authentication\n          </button>\n          <button\n            onClick={() => setActiveTab(\'payments\')}');

code = code.replace('</div>\n          ) : null}', '</div>\n          ) : activeTab === \'payments\' ? (\n            <div className="space-y-4">\n              <h3 className="text-lg font-bold text-hall-900 dark:text-ink">Payment Integrations</h3>\n              <p className="text-sm text-hall-500 dark:text-hall-400 mb-4">Configure Stripe API keys to enable checkout and payment features.</p>\n              \n              <div className="space-y-4">\n                <div>\n                  <label className="block text-sm font-medium text-hall-700 dark:text-hall-300 mb-1">Stripe Publishable Key</label>\n                  <input\n                    type="text"\n                    value={stripePublishableKey}\n                    onChange={(e) => setStripePublishableKey(e.target.value)}\n                    placeholder="pk_test_..."\n                    className="w-full bg-hall-50 dark:bg-black border border-hall-200 dark:border-hall-800 rounded-lg px-3 py-2 text-sm text-hall-900 dark:text-ink focus:ring-2 focus:ring-indigo-500"\n                  />\n                </div>\n                <div>\n                  <label className="block text-sm font-medium text-hall-700 dark:text-hall-300 mb-1">Stripe Secret Key</label>\n                  <input\n                    type="password"\n                    value={stripeSecretKey}\n                    onChange={(e) => setStripeSecretKey(e.target.value)}\n                    placeholder="sk_test_..."\n                    className="w-full bg-hall-50 dark:bg-black border border-hall-200 dark:border-hall-800 rounded-lg px-3 py-2 text-sm text-hall-900 dark:text-ink focus:ring-2 focus:ring-indigo-500"\n                  />\n                </div>\n              </div>\n            </div>\n          ) : null}');

fs.writeFileSync(file, code);
