import { Hono } from 'hono';
import { projectStore } from '../services/project-store.js';

export const deployRoutes = new Hono();

// Helper to generate files for Vercel
const generateVercelFiles = (project: any, framework: string, filesToExport: any[]) => {
  const files: { file: string; data: string }[] = [];
  
  const seoTitle = project.seo?.title || project.name;
  const seoDescription = project.seo?.description || 'Generated by Stagework Forge';
  const seoFavicon = project.seo?.faviconUrl ? `\n    <link rel="icon" href="${project.seo.faviconUrl}" />` : '';
  const seoOgImage = project.seo?.ogImage ? `\n    <meta property="og:image" content="${project.seo.ogImage}" />` : '';
  const seoCustomMeta = project.seo?.metaTags ? `\n    ${project.seo.metaTags}` : '';

  if (framework === 'nextjs') {
    files.push({
      file: 'package.json',
      data: JSON.stringify({
        name: project.name.replace(/[^a-z0-9]/gi, '-').toLowerCase(),
        version: "0.1.0",
        private: true,
        scripts: {
          "dev": "next dev",
          "build": "next build",
          "start": "next start"
        },
        dependencies: {
          "next": "14.2.5",
          "react": "^18",
          "react-dom": "^18",
          "lucide-react": "^0.400.0"
        },
        devDependencies: {
          "tailwindcss": "^3.4.1",
          "postcss": "^8",
          "autoprefixer": "^10.0.1"
        }
      }, null, 2)
    });

    files.push({
      file: 'tailwind.config.js',
      data: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`
    });

    files.push({
      file: 'app/globals.css',
      data: `@tailwind base;\n@tailwind components;\n@tailwind utilities;`
    });

    files.push({
      file: 'app/layout.jsx',
      data: `import './globals.css'\n\nexport const metadata = {\n  title: '${seoTitle}',\n  description: '${seoDescription}',\n}\n\nexport default function RootLayout({ children }) {\n  return (\n    <html lang="en">\n      <head>\n        ${seoFavicon}\n        ${seoOgImage}\n        ${seoCustomMeta}\n      </head>\n      <body>{children}</body>\n    </html>\n  )\n}`
    });

    let mainHtml = filesToExport.find((f: any) => f.name === 'index.html' || f.name.endsWith('.html'));
    if (mainHtml) {
      const bodyMatch = mainHtml.content.match(/<body[^>]*>([\s\S]*)<\/body>/i);
      const content = bodyMatch ? bodyMatch[1] : mainHtml.content;
      const jsxContent = content.replace(/class=/g, 'className=');

      files.push({
        file: 'app/page.jsx',
        data: `export default function Home() {\n  return (\n    <>\n      ${jsxContent}\n    </>\n  )\n}`
      });
    }

  } else if (framework === 'vite') {
    files.push({
      file: 'package.json',
      data: JSON.stringify({
        name: project.name.replace(/[^a-z0-9]/gi, '-').toLowerCase(),
        private: true,
        version: "0.0.0",
        type: "module",
        scripts: {
          "dev": "vite",
          "build": "vite build",
          "preview": "vite preview"
        },
        dependencies: {
          "react": "^18.3.1",
          "react-dom": "^18.3.1",
          "lucide-react": "^0.400.0"
        },
        devDependencies: {
          "@vitejs/plugin-react": "^4.3.1",
          "vite": "^5.3.1",
          "tailwindcss": "^3.4.4",
          "postcss": "^8.4.38",
          "autoprefixer": "^10.4.19"
        }
      }, null, 2)
    });

    files.push({
      file: 'vite.config.js',
      data: `import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  plugins: [react()],\n})`
    });

    files.push({
      file: 'tailwind.config.js',
      data: `/** @type {import('tailwindcss').Config} */\nexport default {\n  content: [\n    "./index.html",\n    "./src/**/*.{js,ts,jsx,tsx}",\n  ],\n  theme: {\n    extend: {},\n  },\n  plugins: [],\n}`
    });

    files.push({
      file: 'src/index.css',
      data: `@tailwind base;\n@tailwind components;\n@tailwind utilities;`
    });

    files.push({
      file: 'src/main.jsx',
      data: `import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App.jsx'\nimport './index.css'\n\nReactDOM.createRoot(document.getElementById('root')).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n)`
    });

    let mainHtml = filesToExport.find((f: any) => f.name === 'index.html' || f.name.endsWith('.html'));
    if (mainHtml) {
      const bodyMatch = mainHtml.content.match(/<body[^>]*>([\s\S]*)<\/body>/i);
      const content = bodyMatch ? bodyMatch[1] : mainHtml.content;
      const jsxContent = content.replace(/class=/g, 'className=');

      files.push({
        file: 'src/App.jsx',
        data: `import React from 'react'\n\nfunction App() {\n  return (\n    <>\n      ${jsxContent}\n    </>\n  )\n}\n\nexport default App`
      });
    }

    files.push({
      file: 'index.html',
      data: `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${seoTitle}</title>\n    <meta name="description" content="${seoDescription}" />${seoFavicon}${seoOgImage}${seoCustomMeta}\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.jsx"></script>\n  </body>\n</html>`
    });

  } else {
    // HTML
    filesToExport.forEach((file: any) => {
      if (file.type !== 'image' && !file.content.startsWith('data:image')) {
        let content = file.content;
        if (file.name === 'index.html' || file.name.endsWith('.html')) {
          const headInjection = `\n    <title>${seoTitle}</title>\n    <meta name="description" content="${seoDescription}" />${seoFavicon}${seoOgImage}${seoCustomMeta}`;
          if (content.includes('</head>')) {
            content = content.replace('</head>', `${headInjection}\n  </head>`);
          }
        }
        files.push({ file: file.name, data: content });
      }
    });
  }

  return files;
};

deployRoutes.get('/vercel/:id', async (c) => {
  const id = c.req.param('id');
  const framework = c.req.query('framework') || 'html';
  
  const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Deploy to Vercel</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #000; color: #fff; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; margin: 0; }
        .container { background: #111; padding: 40px; border-radius: 12px; border: 1px solid #333; width: 100%; max-width: 400px; text-align: center; }
        h1 { font-size: 24px; font-weight: 500; margin-bottom: 8px; }
        p { color: #888; font-size: 14px; margin-bottom: 24px; }
        input { width: 100%; padding: 12px; border-radius: 6px; border: 1px solid #333; background: #000; color: #fff; margin-bottom: 16px; box-sizing: border-box; }
        button { width: 100%; padding: 12px; border-radius: 6px; border: none; background: #fff; color: #000; font-weight: 600; cursor: pointer; transition: all 0.2s; }
        button:hover { background: #ccc; }
        .loader { border: 3px solid #333; border-top: 3px solid #fff; border-radius: 50%; width: 20px; height: 20px; animation: spin 1s linear infinite; display: none; margin: 0 auto; }
        @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
        .success { display: none; flex-direction: column; align-items: center; }
        .success svg { width: 48px; height: 48px; color: #fff; margin-bottom: 16px; }
        .success a { color: #fff; text-decoration: none; margin-top: 16px; border: 1px solid #333; padding: 8px 16px; border-radius: 4px; transition: all 0.2s; }
        .success a:hover { background: #111; border-color: #fff; }
        .error { color: #ff4444; font-size: 14px; margin-top: 16px; display: none; }
      </style>
    </head>
    <body>
      <div class="container" id="form-container">
        <svg viewBox="0 0 76 65" fill="none" xmlns="http://www.w3.org/2000/svg" style="width: 48px; height: 48px; margin-bottom: 16px;"><path d="M37.5274 0L75.0548 65H0L37.5274 0Z" fill="currentColor"/></svg>
        <h1>Deploy to Vercel</h1>
        <p>Enter your Vercel Personal Access Token to deploy this project.</p>
        <input type="password" id="token" placeholder="Vercel Token (e.g., vk1_...)" />
        <button id="deploy-btn" onclick="deploy()">Deploy Project</button>
        <div class="loader" id="loader"></div>
        <div class="error" id="error"></div>
      </div>
      
      <div class="container success" id="success-container">
        <svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <h1>Deployment Successful</h1>
        <p>Your project is now live on the edge.</p>
        <a id="deployment-url" href="#" target="_blank">Visit Deployment</a>
      </div>
      
      <script>
        async function deploy() {
          const token = document.getElementById('token').value;
          if (!token) return alert('Token is required');
          
          document.getElementById('deploy-btn').style.display = 'none';
          document.getElementById('loader').style.display = 'block';
          document.getElementById('error').style.display = 'none';
          
          try {
            const res = await fetch(\`/api/deploy/vercel/${id}?framework=${framework}\`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ token })
            });
            
            const data = await res.json();
            
            if (res.ok) {
              document.getElementById('form-container').style.display = 'none';
              document.getElementById('success-container').style.display = 'flex';
              document.getElementById('deployment-url').href = data.url;
            } else {
              throw new Error(data.error || 'Deployment failed');
            }
          } catch (err) {
            document.getElementById('deploy-btn').style.display = 'block';
            document.getElementById('loader').style.display = 'none';
            document.getElementById('error').textContent = err.message;
            document.getElementById('error').style.display = 'block';
          }
        }
      </script>
    </body>
    </html>
  `;
  
  return c.html(html);
});

deployRoutes.post('/vercel/:id', async (c) => {
  try {
    const id = c.req.param('id');
    const framework = c.req.query('framework') || 'html';
    const { token } = await c.req.json();
    
    if (!token) {
      return c.json({ error: 'Vercel token is required' }, 400);
    }

    const project = await projectStore.get(id);
    if (!project) {
      return c.json({ error: 'Project not found' }, 404);
    }

    let filesToExport = [];
    if (project.mutations && project.mutations.length > 0) {
      const latestMutation = project.mutations[project.mutations.length - 1];
      if (latestMutation.files) {
        filesToExport = latestMutation.files;
      }
    }

    if (filesToExport.length === 0) {
      return c.json({ error: 'No files generated for this project yet' }, 400);
    }

    const files = generateVercelFiles(project, framework, filesToExport);
    
    // Map framework for Vercel projectSettings
    let vercelFramework = null;
    if (framework === 'nextjs') vercelFramework = 'nextjs';
    else if (framework === 'vite') vercelFramework = 'vite';

    const projectName = project.name.replace(/[^a-z0-9]/gi, '-').toLowerCase().substring(0, 50) || 'stagework-project';

    const response = await fetch('https://api.vercel.com/v13/deployments', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: projectName,
        files: files,
        projectSettings: {
          framework: vercelFramework
        }
      })
    });

    const data = await response.json();

    if (!response.ok) {
      console.error('Vercel deployment failed:', data);
      return c.json({ error: data.error?.message || 'Vercel deployment failed' }, response.status as any);
    }

    return c.json({ 
      success: true, 
      url: `https://${data.url}`,
      deploymentId: data.id 
    });

  } catch (error) {
    console.error('Deploy error:', error);
    return c.json({ error: 'Failed to deploy project' }, 500);
  }
});


deployRoutes.get('/github/:id', async (c) => {
  const id = c.req.param('id');
  const framework = c.req.query('framework') || 'html';
  
  const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Push to GitHub</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #000; color: #fff; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; margin: 0; }
        .container { background: #111; padding: 40px; border-radius: 12px; border: 1px solid #333; width: 100%; max-width: 400px; text-align: center; }
        h1 { font-size: 24px; font-weight: 500; margin-bottom: 8px; }
        p { color: #888; font-size: 14px; margin-bottom: 24px; }
        input { width: 100%; padding: 12px; border-radius: 6px; border: 1px solid #333; background: #000; color: #fff; margin-bottom: 16px; box-sizing: border-box; }
        button { width: 100%; padding: 12px; border-radius: 6px; border: none; background: #fff; color: #000; font-weight: 600; cursor: pointer; transition: all 0.2s; }
        button:hover { background: #ccc; }
        .loader { border: 3px solid #333; border-top: 3px solid #fff; border-radius: 50%; width: 20px; height: 20px; animation: spin 1s linear infinite; display: none; margin: 0 auto; }
        @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
        .success { display: none; flex-direction: column; align-items: center; }
        .success svg { width: 48px; height: 48px; color: #fff; margin-bottom: 16px; }
        .success a { color: #fff; text-decoration: none; margin-top: 16px; border: 1px solid #333; padding: 8px 16px; border-radius: 4px; transition: all 0.2s; }
        .success a:hover { background: #111; border-color: #fff; }
        .error { color: #ff4444; font-size: 14px; margin-top: 16px; display: none; }
      </style>
    </head>
    <body>
      <div class="container" id="form-container">
        <svg viewBox="0 0 24 24" fill="currentColor" style="width: 48px; height: 48px; margin-bottom: 16px;"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <h1>Push to GitHub</h1>
        <p>Enter your GitHub Personal Access Token (classic with repo scope or fine-grained).</p>
        <input type="password" id="token" placeholder="GitHub Token (e.g., ghp_...)" />
        <button id="deploy-btn" onclick="deploy()">Push Project</button>
        <div class="loader" id="loader"></div>
        <div class="error" id="error"></div>
      </div>
      
      <div class="container success" id="success-container">
        <svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <h1>Repository Created</h1>
        <p>Your project has been successfully pushed to GitHub.</p>
        <a id="deployment-url" href="#" target="_blank">View Repository</a>
      </div>
      
      <script>
        async function deploy() {
          const token = document.getElementById('token').value;
          if (!token) return alert('Token is required');
          
          document.getElementById('deploy-btn').style.display = 'none';
          document.getElementById('loader').style.display = 'block';
          document.getElementById('error').style.display = 'none';
          
          try {
            const res = await fetch(\`/api/deploy/github/\${id}?framework=\${framework}\`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ token })
            });
            
            const data = await res.json();
            
            if (res.ok) {
              document.getElementById('form-container').style.display = 'none';
              document.getElementById('success-container').style.display = 'flex';
              document.getElementById('deployment-url').href = data.url;
            } else {
              throw new Error(data.error || 'Push failed');
            }
          } catch (err) {
            document.getElementById('deploy-btn').style.display = 'block';
            document.getElementById('loader').style.display = 'none';
            document.getElementById('error').textContent = err.message;
            document.getElementById('error').style.display = 'block';
          }
        }
      </script>
    </body>
    </html>
  `;
  
  return c.html(html);
});

deployRoutes.post('/domain/:id', async (c) => {
  try {
    const id = c.req.param('id');
    const { domain } = await c.req.json();
    const project = await projectStore.get(id);
    
    if (!project) {
      return c.json({ error: 'Project not found' }, 404);
    }

    if (!domain) {
      return c.json({ error: 'Domain is required' }, 400);
    }

    await projectStore.save({ id, customDomain: domain });
    return c.json({ 
      success: true, 
      domain, 
      message: `Domain ${domain} configured successfully. DNS verification pending.` 
    });

  } catch (error) {
    console.error('Domain config error:', error);
    return c.json({ error: 'Failed to configure custom domain' }, 500);
  }
});

deployRoutes.get('/domain/:id', async (c) => {
  try {
    const id = c.req.param('id');
    const project = await projectStore.get(id);
    
    if (!project) {
      return c.json({ error: 'Project not found' }, 404);
    }

    const mockDomain = project.customDomain || null;
    
    return c.json({ 
      domain: mockDomain 
    });

  } catch (error) {
    console.error('Domain fetch error:', error);
    return c.json({ error: 'Failed to fetch custom domain' }, 500);
  }
});

deployRoutes.get('/netlify/:id', async (c) => {
  const id = c.req.param('id');
  const framework = c.req.query('framework') || 'html';
  
  const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Deploy to Netlify</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #000; color: #fff; display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100vh; margin: 0; }
        .container { background: #111; padding: 40px; border-radius: 12px; border: 1px solid #333; width: 100%; max-width: 400px; text-align: center; }
        h1 { font-size: 24px; font-weight: 500; margin-bottom: 8px; }
        p { color: #888; font-size: 14px; margin-bottom: 24px; }
        input { width: 100%; padding: 12px; border-radius: 6px; border: 1px solid #333; background: #000; color: #fff; margin-bottom: 16px; box-sizing: border-box; }
        button { width: 100%; padding: 12px; border-radius: 6px; border: none; background: #00c7b7; color: #fff; font-weight: 600; cursor: pointer; transition: all 0.2s; }
        button:hover { background: #00b3a4; }
        .loader { border: 3px solid #333; border-top: 3px solid #00c7b7; border-radius: 50%; width: 20px; height: 20px; animation: spin 1s linear infinite; display: none; margin: 0 auto; }
        @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
        .success { display: none; flex-direction: column; align-items: center; }
        .success svg { width: 48px; height: 48px; color: #00c7b7; margin-bottom: 16px; }
        .success a { color: #fff; text-decoration: none; margin-top: 16px; border: 1px solid #333; padding: 8px 16px; border-radius: 4px; transition: all 0.2s; }
        .success a:hover { background: #111; border-color: #00c7b7; }
        .error { color: #ff4444; font-size: 14px; margin-top: 16px; display: none; }
      </style>
    </head>
    <body>
      <div class="container" id="form-container">
        <svg viewBox="0 0 115 115" fill="none" xmlns="http://www.w3.org/2000/svg" style="width: 48px; height: 48px; margin-bottom: 16px;"><path d="M57.5 115C89.2564 115 115 89.2564 115 57.5C115 25.7436 89.2564 0 57.5 0C25.7436 0 0 25.7436 0 57.5C0 89.2564 25.7436 115 57.5 115Z" fill="#00C7B7"/><path d="M25 57.5L57.5 25L90 57.5L57.5 90L25 57.5Z" fill="white"/></svg>
        <h1>Deploy to Netlify</h1>
        <p>Enter your Netlify Personal Access Token to deploy this project.</p>
        <input type="password" id="token" placeholder="Netlify Token (e.g., nfp_...)" />
        <button id="deploy-btn" onclick="deploy()">Deploy Project</button>
        <div class="loader" id="loader"></div>
        <div class="error" id="error"></div>
      </div>
      
      <div class="container success" id="success-container">
        <svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <h1>Deployment Successful</h1>
        <p>Your project is now live on Netlify.</p>
        <a id="deployment-url" href="#" target="_blank">Visit Deployment</a>
      </div>
      
      <script>
        async function deploy() {
          const token = document.getElementById('token').value;
          if (!token) return alert('Token is required');
          
          document.getElementById('deploy-btn').style.display = 'none';
          document.getElementById('loader').style.display = 'block';
          document.getElementById('error').style.display = 'none';
          
          try {
            const res = await fetch(\`/api/deploy/netlify/${id}?framework=${framework}\`, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ token })
            });
            
            const data = await res.json();
            
            if (res.ok) {
              document.getElementById('form-container').style.display = 'none';
              document.getElementById('success-container').style.display = 'flex';
              document.getElementById('deployment-url').href = data.url;
            } else {
              throw new Error(data.error || 'Deployment failed');
            }
          } catch (err) {
            document.getElementById('deploy-btn').style.display = 'block';
            document.getElementById('loader').style.display = 'none';
            document.getElementById('error').textContent = err.message;
            document.getElementById('error').style.display = 'block';
          }
        }
      </script>
    </body>
    </html>
  `;
  
  return c.html(html);
});

import archiver from 'archiver';
import { PassThrough } from 'stream';

deployRoutes.post('/netlify/:id', async (c) => {
  try {
    const id = c.req.param('id');
    const framework = c.req.query('framework') || 'html';
    const { token } = await c.req.json();
    
    if (!token) {
      return c.json({ error: 'Netlify token is required' }, 400);
    }

    const project = await projectStore.get(id);
    if (!project) {
      return c.json({ error: 'Project not found' }, 404);
    }

    let filesToExport = [];
    if (project.mutations && project.mutations.length > 0) {
      const latestMutation = project.mutations[project.mutations.length - 1];
      if (latestMutation.files) {
        filesToExport = latestMutation.files;
      }
    }

    if (filesToExport.length === 0) {
      return c.json({ error: 'No files generated for this project yet' }, 400);
    }

    const files = generateVercelFiles(project, framework, filesToExport); // Re-use the file generator logic
    
    // Create a zip buffer in memory
    const archive = archiver('zip', { zlib: { level: 9 } });
    const pass = new PassThrough();
    
    const chunks: Buffer[] = [];
    pass.on('data', (chunk) => chunks.push(Buffer.from(chunk)));
    
    const zipPromise = new Promise<Buffer>((resolve, reject) => {
      pass.on('end', () => resolve(Buffer.concat(chunks)));
      pass.on('error', reject);
      archive.on('error', reject);
    });

    archive.pipe(pass);

    for (const file of files) {
      archive.append(file.data, { name: file.file });
    }

    await archive.finalize();
    const zipBuffer = await zipPromise;

    // Create a new site if we don't have one, or deploy to an existing one
    // For simplicity, we create a new site for each deployment in this implementation
    const projectName = project.name.replace(/[^a-z0-9]/gi, '-').toLowerCase().substring(0, 50) || 'stagework-project';

    const createSiteResponse = await fetch('https://api.netlify.com/api/v1/sites', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: `${projectName}-${Math.random().toString(36).substring(7)}`,
        custom_domain: project.customDomain || undefined
      })
    });

    const siteData = await createSiteResponse.json();

    if (!createSiteResponse.ok) {
      console.error('Netlify site creation failed:', siteData);
      return c.json({ error: siteData.message || 'Netlify site creation failed' }, createSiteResponse.status as any);
    }

    const siteId = siteData.id;

    // Deploy the zip file
    const deployResponse = await fetch(`https://api.netlify.com/api/v1/sites/${siteId}/deploys`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/zip',
      },
      body: zipBuffer as unknown as BodyInit
    });

    const deployData = await deployResponse.json();

    if (!deployResponse.ok) {
      console.error('Netlify deployment failed:', deployData);
      return c.json({ error: deployData.message || 'Netlify deployment failed' }, deployResponse.status as any);
    }

    return c.json({ 
      success: true, 
      url: deployData.url || siteData.url,
      deploymentId: deployData.id 
    });

  } catch (error) {
    console.error('Deploy error:', error);
    return c.json({ error: 'Failed to deploy project to Netlify' }, 500);
  }
});

deployRoutes.post('/github/:id', async (c) => {
  try {
    const id = c.req.param('id');
    const framework = c.req.query('framework') || 'html';
    const { token } = await c.req.json();
    
    if (!token) {
      return c.json({ error: 'GitHub token is required' }, 400);
    }

    const project = await projectStore.get(id);
    if (!project) {
      return c.json({ error: 'Project not found' }, 404);
    }

    let filesToExport = [];
    if (project.mutations && project.mutations.length > 0) {
      const latestMutation = project.mutations[project.mutations.length - 1];
      if (latestMutation.files) {
        filesToExport = latestMutation.files;
      }
    }

    if (filesToExport.length === 0) {
      return c.json({ error: 'No files generated for this project yet' }, 400);
    }

    const files = generateVercelFiles(project, framework, filesToExport);
    
    // 1. Get user info
    const userRes = await fetch('https://api.github.com/user', {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'Stagework-Forge-App'
      }
    });

    if (!userRes.ok) {
      return c.json({ error: 'Invalid GitHub token or insufficient permissions' }, 401);
    }
    const userData = await userRes.json();
    const username = userData.login;

    // 2. Create Repository
    const repoName = project.name.replace(/[^a-z0-9]/gi, '-').toLowerCase() + '-' + Math.random().toString(36).substring(7);
    const createRepoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent': 'Stagework-Forge-App'
      },
      body: JSON.stringify({
        name: repoName,
        description: project.seo?.description || 'Generated by Stagework Forge',
        private: false,
        auto_init: true
      })
    });

    if (!createRepoRes.ok) {
      const errorData = await createRepoRes.json();
      return c.json({ error: errorData.message || 'Failed to create repository' }, createRepoRes.status as any);
    }

    const repoData = await createRepoRes.json();

    // 3. Commit files using the Tree API for multi-file commit
    // a. Get current branch ref
    const refRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/refs/heads/main`, {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'Stagework-Forge-App'
      }
    });
    
    if (!refRes.ok) {
      return c.json({ error: 'Failed to fetch repository reference' }, 500);
    }
    const refData = await refRes.json();
    const commitSha = refData.object.sha;

    // b. Get the commit to get the tree sha
    const commitRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/commits/${commitSha}`, {
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'Stagework-Forge-App'
      }
    });
    const commitData = await commitRes.json();
    const baseTreeSha = commitData.tree.sha;

    // c. Create a new tree
    const treePayload = {
      base_tree: baseTreeSha,
      tree: files.map(f => ({
        path: f.file,
        mode: '100644',
        type: 'blob',
        content: f.data
      }))
    };

    const createTreeRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/trees`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent': 'Stagework-Forge-App'
      },
      body: JSON.stringify(treePayload)
    });
    const treeData = await createTreeRes.json();
    const newTreeSha = treeData.sha;

    // d. Create a new commit
    const createCommitRes = await fetch(`https://api.github.com/repos/${username}/${repoName}/git/commits`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent': 'Stagework-Forge-App'
      },
      body: JSON.stringify({
        message: 'Initial commit from Stagework Forge',
        tree: newTreeSha,
        parents: [commitSha]
      })
    });
    const newCommitData = await createCommitRes.json();
    const newCommitSha = newCommitData.sha;

    // e. Update the ref
    await fetch(`https://api.github.com/repos/${username}/${repoName}/git/refs/heads/main`, {
      method: 'PATCH',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Accept': 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent': 'Stagework-Forge-App'
      },
      body: JSON.stringify({
        sha: newCommitSha,
        force: true
      })
    });

    return c.json({ 
      success: true, 
      url: repoData.html_url
    });

  } catch (error) {
    console.error('GitHub deploy error:', error);
    return c.json({ error: 'Failed to push project to GitHub' }, 500);
  }
});
