import { Hono } from 'hono';
import { projectStore } from '../services/project-store.js';
import archiver from 'archiver';
import { stream } from 'hono/streaming';
import { PassThrough } from 'stream';

export const exportRoutes = new Hono();

exportRoutes.get('/:id', async (c) => {
  try {
    const id = c.req.param('id');
    const framework = c.req.query('framework') || 'html'; // html, vite, nextjs
    const project = await projectStore.get(id);
    
    if (!project) {
      return c.json({ error: 'Project not found' }, 404);
    }

    let filesToExport = [];
    if (project.mutations && project.mutations.length > 0) {
      const latestMutation = project.mutations[project.mutations.length - 1];
      if (latestMutation.files) {
        filesToExport = latestMutation.files;
      }
    }

    if (filesToExport.length === 0) {
      return c.json({ error: 'No files generated for this project yet' }, 400);
    }

    const archive = archiver('zip', {
      zlib: { level: 9 }
    });

    const pass = new PassThrough();
    archive.pipe(pass);

    const zipFilename = `${project.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${framework}_export.zip`;

    c.header('Content-Type', 'application/zip');
    c.header('Content-Disposition', `attachment; filename="${zipFilename}"`);

    // Build the archive contents
    if (framework === 'nextjs') {
      archive.append(JSON.stringify({
        name: project.name.replace(/[^a-z0-9]/gi, '-').toLowerCase(),
        version: "0.1.0",
        private: true,
        scripts: {
          "dev": "next dev",
          "build": "next build",
          "start": "next start"
        },
        dependencies: {
          "next": "14.2.5",
          "react": "^18",
          "react-dom": "^18",
          "lucide-react": "^0.400.0"
        },
        devDependencies: {
          "tailwindcss": "^3.4.1",
          "postcss": "^8",
          "autoprefixer": "^10.0.1"
        }
      }, null, 2), { name: 'package.json' });

      archive.append(`/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`, { name: 'tailwind.config.js' });

      archive.append(`@tailwind base;
@tailwind components;
@tailwind utilities;`, { name: 'app/globals.css' });

      archive.append(`import './globals.css'

export const metadata = {
  title: '${project.name}',
  description: 'Generated by Stagework Forge',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`, { name: 'app/layout.jsx' });

      let mainHtml = filesToExport.find((f: any) => f.name === 'index.html' || f.name.endsWith('.html'));
      if (mainHtml) {
        // Extract body content roughly
        const bodyMatch = mainHtml.content.match(/<body[^>]*>([\s\S]*)<\/body>/i);
        const content = bodyMatch ? bodyMatch[1] : mainHtml.content;
        
        // Convert class= to className=
        const jsxContent = content.replace(/class=/g, 'className=');

        archive.append(`export default function Home() {
  return (
    <>
      ${jsxContent}
    </>
  )
}`, { name: 'app/page.jsx' });
      }

    } else if (framework === 'vite') {
      archive.append(JSON.stringify({
        name: project.name.replace(/[^a-z0-9]/gi, '-').toLowerCase(),
        private: true,
        version: "0.0.0",
        type: "module",
        scripts: {
          "dev": "vite",
          "build": "vite build",
          "preview": "vite preview"
        },
        dependencies: {
          "react": "^18.3.1",
          "react-dom": "^18.3.1",
          "lucide-react": "^0.400.0"
        },
        devDependencies: {
          "@vitejs/plugin-react": "^4.3.1",
          "vite": "^5.3.1",
          "tailwindcss": "^3.4.4",
          "postcss": "^8.4.38",
          "autoprefixer": "^10.4.19"
        }
      }, null, 2), { name: 'package.json' });

      archive.append(`import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})`, { name: 'vite.config.js' });

      archive.append(`/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`, { name: 'tailwind.config.js' });

      archive.append(`@tailwind base;
@tailwind components;
@tailwind utilities;`, { name: 'src/index.css' });

      archive.append(`import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`, { name: 'src/main.jsx' });

      let mainHtml = filesToExport.find((f: any) => f.name === 'index.html' || f.name.endsWith('.html'));
      if (mainHtml) {
        const bodyMatch = mainHtml.content.match(/<body[^>]*>([\s\S]*)<\/body>/i);
        const content = bodyMatch ? bodyMatch[1] : mainHtml.content;
        const jsxContent = content.replace(/class=/g, 'className=');

        archive.append(`import React from 'react'

function App() {
  return (
    <>
      ${jsxContent}
    </>
  )
}

export default App`, { name: 'src/App.jsx' });
      }

      archive.append(`<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${project.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`, { name: 'index.html' });

    } else {
      // Default HTML export
      filesToExport.forEach((file: any) => {
         if (file.type === 'image' || file.content.startsWith('data:image')) {
            const parts = file.content.split(',');
            if (parts.length >= 2) {
              const buffer = Buffer.from(parts[1], 'base64');
              archive.append(buffer, { name: file.name });
            }
         } else {
            archive.append(file.content, { name: file.name });
         }
      });
    }

    archive.finalize();

    return stream(c, async (stream) => {
      for await (const chunk of pass) {
        await stream.write(chunk);
      }
    });

  } catch (err: any) {
    console.error("Export error:", err);
    return c.json({ error: err.message }, 500);
  }
});
